Seb2
Senior-Software-Project/friendly-barnacle pull request #65
Opened 2022-04-16 20:49 UTC by SebastianSafaiRad

Started working on doc strings using JSDoc. Got a good start on all of the files under the views category.  In order to use JSDoc you must install globally using "npm install -g jsdoc".  Then you can run using "jsdoc file.js".  Doc Strings using This merge should have no conflicts

2022-04-16 21:45 UTC, JonathanGrant92 requested changes
Please add 'views/out/` to the top of the .gitignore file. Then run 'git rm --cached -r views/out/`. Then commit and push to repo/Seb2 again.

2022-04-16 22:32 UTC, JonathanGrant92 commented
Please don't run `npm i -g jsdoc` because jsdoc is a development dependency. Run`npm i` to update project environment with newest `package.json`. Developer tools should be installed either as `npm i -g --save-dev jsdoc` or `npm i --save-dev jsdoc`.  The `-g` is the global flag, if you want to install globally, not in a specific project environment.

2022-04-17 00:26 UTC, JonathanGrant92 approved these changes
Looks good!

2022-04-17 01:43 UTC, JonathanGrant92 commented on views/Home.js
Missing `}`. Sorry, I accidentally did this when merging conflicts!

2022-04-19 02:40 UTC, NoelC9 approved these changes
Thanks for adding comments.

2022-04-19 03:32 UTC, merged